import test from 'node:test';
import assert from 'node:assert/strict';
import 'fake-indexeddb/auto';
import * as offline from './offline.js';
const memory = new Map(), locks = new Map();
Object.defineProperty(globalThis, 'navigator', { configurable: true, value: { onLine: false, locks: { request(key, fn) { const next = (locks.get(key) || Promise.resolve()).then(fn); locks.set(key, next.catch(() => {})); return next; } } } });
globalThis.localStorage = { getItem: key => memory.get(key), setItem: (key, value) => memory.set(key, value), removeItem: key => memory.delete(key) };
globalThis.window = new EventTarget();
const admin = { id: 'owner-a', role: 'admin' }, other = { id: 'owner-b', role: 'admin' };
let actor = admin.id, failure, calls = [], receipts = new Map();
let scanned = { id: 'valve-qr', name: 'Válvula de prueba', kind: 'valve', current_active: false };
offline.configureOffline({ auth: { getUser: async () => ({ data: { user: { id: actor } } }) }, rpc: async (name, params) => {
  calls.push({ name, params });
  if (failure === 'throw-network') throw new TypeError('Failed to fetch');
  if (failure) return { error: { message: failure } };
  if (name === 'irrigation_scanned_device') return { data: scanned ? [scanned] : [] };
  if (!receipts.has(params.p_request_id)) receipts.set(params.p_request_id, name === 'apply_offline_change' ? { ...params.p_payload, id: params.p_id, created_date: 'server-date' } : { id: params.p_request_id, device_id: params.p_device_id, active: params.p_active, occurred_at: params.p_occurred_at });
  return { data: receipts.get(params.p_request_id) };
} });

test('offline lifecycle: durable ordered writes, owner isolation, conflicts and retry', async () => {
  await offline.setOfflineUser(admin);
  navigator.onLine = true;
  await offline.entityRead('lots', 'all', async () => [{ id: 'lot-1', name: 'Antes' }]);
  const page = await offline.entityRead('sensor_readings', 'page2', async () => [{ id: 'reading-1001', timestamp: '2026-09-30' }], {}, '-timestamp', 1000, 1000, true);
  assert.equal(page.length, 1, 'server page must not be sliced a second time');
  navigator.onLine = false;
  await offline.entityWrite('lots', 'update', 'lot-1', { name: 'Después' });
  await offline.entityWrite('lots', 'update', 'lot-1', { name: 'Final' });
  let queue = await offline.pendingOperations();
  assert.equal(queue.length, 2); assert.ok(queue[0].order < queue[1].order);
  assert.deepEqual(queue[1].expected, { name: 'Después' });
  const reloaded = await import('./offline.js?reload');
  assert.deepEqual(await reloaded.cachedUser(), admin);
  await reloaded.setOfflineUser(await reloaded.cachedUser());
  assert.equal((await reloaded.pendingOperations()).length, 2, 'fresh module retains IndexedDB queue');
  assert.equal((await offline.entityRead('lots', 'all', () => assert.fail('must not fetch offline')))[0].name, 'Final');
  await offline.setOfflineUser(other);
  assert.equal((await offline.pendingOperations()).length, 0);
  await assert.rejects(offline.snapshot('entity:lots:all', () => []), /no están descargados/);
  await offline.setOfflineUser(admin);
  navigator.onLine = true; actor = other.id;
  await offline.flushOffline(); assert.equal(calls.length, 0, 'different server identity cannot replay another owner');
  actor = admin.id; failure = 'El registro cambió en otro dispositivo';
  await offline.flushOffline(); assert.equal((await offline.pendingOperations()).length, 2);
  assert.match(offline.offlineState.error, /otro dispositivo/);
  failure = null;
  await Promise.all([offline.retryOffline(), offline.flushOffline()]);
  assert.equal((await offline.pendingOperations()).length, 0);
  assert.equal(receipts.size, 2);
  navigator.onLine = false;
  assert.equal((await offline.entityRead('lots', 'all', () => []))[0].name, 'Final', 'acknowledged changes remain visible offline');
  await offline.setOfflineUser({ id: admin.id, role: 'regador' });
  await assert.rejects(offline.entityWrite('lots', 'create', null, { name: 'Denied' }), /administrador/);
  const moment = '2026-09-30T10:00:00.000Z';
  const opened = await offline.offlineIrrigationAction('valve-1', true, 'open-request', moment);
  await offline.offlineIrrigationAction('valve-1', false, 'close-request', '2026-09-30T11:00:00.000Z');
  assert.equal(opened.occurred_at, moment); assert.equal(opened._offline_pending, true);
  queue = await offline.pendingOperations(); assert.deepEqual(queue.map(x => x.active), [true, false]);
  navigator.onLine = true; await offline.flushOffline();
  assert.equal((await offline.pendingOperations()).length, 0);
  const irrigation = calls.filter(x => x.name === 'record_irrigation_offline_action');
  assert.equal(irrigation[0].params.p_occurred_at, moment);
  failure = 'throw-network';
  const interrupted = await offline.offlineIrrigationAction('valve-2', true, 'network-request', moment);
  assert.equal(interrupted._offline_pending, true, 'an interrupted network request still acknowledges the durable local save');
  failure = null; await offline.flushOffline();
  assert.equal((await offline.pendingOperations()).length, 0);

  navigator.onLine = false;
  const unknown = await offline.scannedIrrigationDevice('new-qr', () => assert.fail('offline must not fetch'));
  assert.equal(unknown._offline_unverified, true);
  await offline.offlineIrrigationAction(null, true, 'qr-open', moment, 'new-qr');
  await offline.offlineIrrigationAction(null, false, 'qr-close', moment, 'new-qr');
  assert.equal((await offline.scannedIrrigationDevice('new-qr', () => [] )).current_active, false);
  navigator.onLine = true;
  scanned = null; await offline.flushOffline();
  assert.equal((await offline.pendingOperations()).length, 2, 'invalid QR never loses its pending changes');
  assert.match(offline.offlineState.error, /QR/);
  const callCount = calls.length;
  await offline.flushOffline();
  assert.equal(calls.length, callCount, 'a rejected QR requires explicit retry or review');
  scanned = { id: 'valve-qr', name: 'Válvula de prueba', kind: 'valve', current_active: true };
  await offline.retryOffline();
  assert.equal((await offline.pendingOperations()).length, 0);
  const qrActions = calls.filter(x => x.name === 'record_irrigation_offline_action' && x.params.p_device_id === 'valve-qr');
  assert.deepEqual(qrActions.map(x => x.params.p_active), [true, false]);
  navigator.onLine = false;
  const downloaded = await offline.scannedIrrigationDevice('new-qr', () => []);
  assert.equal(downloaded.name, 'Válvula de prueba');
  assert.equal(downloaded.current_active, false, 'acknowledged QR state remains available after going offline again');
  await offline.setOfflineUser(other);
  assert.equal((await offline.scannedIrrigationDevice('new-qr', () => [] ))._offline_unverified, true, 'scanned equipment cache is isolated by user');
});

test('missing downloaded data is explicit and criteria reflect pending edits', () => {
  const rows = offline.overlay([{ id: '1', farm: 'A', value: 4 }], [{ kind: 'entity', table: 'lots', operation: 'update', id: '1', payload: { value: 8 } }, { kind: 'entity', table: 'lots', operation: 'create', id: '2', payload: { farm: 'B' } }], 'lots');
  assert.equal(rows.filter(row => offline.matches(row, { farm: 'A', value: { $gte: 7 } })).length, 1);
  assert.equal(offline.overlay(rows, [{ kind: 'entity', table: 'lots', operation: 'delete', id: '1' }], 'lots').length, 1);
});
