project_id = "lucient"

[functions.agro-sync]
verify_jwt = false

[functions.fetch-weather-station-data]
verify_jwt = false

[functions.test-weather-station]
verify_jwt = false

[functions.fetch-sentek-probe-data]
verify_jwt = false

[functions.test-sentek-probe]
verify_jwt = false

[functions.sync-all-sentek-probes]
verify_jwt = false

[functions.sync-all-integrations]
verify_jwt = false
