import React,{useState} from 'react';
import { X } from 'lucide-react';
import { backend } from '@/api/backendClient';
export default function LotEditModal({lot,onSaved,onClose}){
  const [form,setForm]=useState({...lot});
  const [busy,setBusy]=useState(false);
  const set=(k,v)=>setForm({...form,[k]:v});
  const VARS={Olivos:['Coratina','Barnea','Hojiblanca','Picual','Arbequina','Arbosana'],Granadas:['Wonderful']};
  const setCrop=c=>setForm({...form,crop:c,variety:(VARS[c]||[''])[0]});
  const num=['area_ha','planting_year','row_spacing','plant_spacing','current_plants'];
  const save=async e=>{e.preventDefault();setBusy(true);
    const payload={};Object.keys(form).forEach(k=>{if(!['id','created_date','updated_date','created_by_id','polygon'].includes(k))payload[k]=num.includes(k)?Number(form[k]||0):form[k]});
    await backend.entities.Lot.update(lot.id,payload);
    await onSaved();setBusy(false);onClose();
  };
  const f=(k,label,type='text')=> <label key={k} className="grid gap-1 text-xs font-bold uppercase text-slate-500">{label}<input type={type} value={form[k]??''} onChange={e=>set(k,e.target.value)} required={k==='name'||k==='farm'||k==='crop'||k==='variety'} className="rounded-lg border px-3 py-2 text-sm normal-case text-slate-800"/></label>;
  return <div className="fixed inset-0 z-[2000] grid place-items-center bg-black/50 p-4"><form onSubmit={save} className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-bold">Editar lote</h2><button type="button" onClick={onClose}><X/></button></div><div className="grid gap-3 sm:grid-cols-2">{f('name','Nombre')}{<label key="farm" className="grid gap-1 text-xs font-bold uppercase text-slate-500">Finca<select value={form.farm??''} onChange={e=>set('farm',e.target.value)} required className="rounded-lg border px-3 py-2 text-sm normal-case text-slate-800"><option value="">Seleccionar…</option><option>Las 500</option><option>Glonet</option><option>Las 115</option></select></label>}{<label key="sector" className="grid gap-1 text-xs font-bold uppercase text-slate-500">Sector<select value={form.sector??''} onChange={e=>set('sector',e.target.value)} className="rounded-lg border px-3 py-2 text-sm normal-case text-slate-800"><option value="">Seleccionar…</option>{['NO','NE','SO','SE','E','C','O'].map(s=><option key={s}>{s}</option>)}</select></label>}{<label key="crop" className="grid gap-1 text-xs font-bold uppercase text-slate-500">Cultivo<select value={form.crop??''} onChange={e=>setCrop(e.target.value)} required className="rounded-lg border px-3 py-2 text-sm normal-case text-slate-800"><option value="">Seleccionar…</option><option>Olivos</option><option>Granadas</option></select></label>}{<label key="variety" className="grid gap-1 text-xs font-bold uppercase text-slate-500">Variedad<select value={form.variety??''} onChange={e=>set('variety',e.target.value)} required className="rounded-lg border px-3 py-2 text-sm normal-case text-slate-800"><option value="">Seleccionar…</option>{(VARS[form.crop]||[]).map(v=><option key={v}>{v}</option>)}</select></label>}{f('planting_year','Año plantación','number')}{f('planting_date','Fecha plantación','date')}{f('area_ha','Superficie (ha)','number')}{f('row_spacing','Marco filas (m)','number')}{f('plant_spacing','Marco plantas (m)','number')}{f('current_plants','Plantas actuales','number')}{f('soil_type','Tipo de suelo')}<label className="grid gap-1 text-xs font-bold uppercase text-slate-500 sm:col-span-2">Notas<textarea value={form.notes??''} onChange={e=>set('notes',e.target.value)} rows="3" className="rounded-lg border px-3 py-2 text-sm normal-case text-slate-800"/></label></div><button disabled={busy} className="mt-5 w-full rounded-xl bg-emerald-900 py-3 font-bold text-white">{busy?'Guardando…':'Guardar cambios'}</button></form></div>;}