import React,{useMemo,useState} from 'react';
import { MapContainer, TileLayer, Polygon, Tooltip } from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import { useNavigate } from 'react-router-dom';
import { useFarm } from '@/lib/FarmContext';
import { lotMetrics } from '@/lib/farmCalculations';
import MapFilters from '@/components/MapFilters';
import LoadingState from '@/components/LoadingState';
const categorical=['#15803d','#2563eb','#7c3aed','#c2410c','#0f766e','#be123c'];
export default function MapPage(){const d=useFarm(),nav=useNavigate(),[view,setView]=useState('Cultivo'),[filters,setFilters]=useState({});const ranges=JSON.parse(localStorage.getItem('mapRanges')||'{"low":30000,"high":38000}');const lots=useMemo(()=> (d.Lot||[]).filter(l=>Object.entries(filters).every(([k,v])=>!v||(k==='age'?String(new Date().getFullYear()-l.planting_year)===v:String(l[k])===v))),[d.Lot,filters]);if(d.loading)return <LoadingState/>;const color=(l)=>{const m=lotMetrics(l,d.ProductionRecord,d.Objective,d.HealthRecord);if(view==='Estado sanitario')return m.healthState==='Bueno'?'#16a34a':m.healthState==='Intermedio'?'#eab308':'#dc2626';if(view==='Problemas sanitarios recurrentes'){const n=d.HealthRecord.filter(h=>h.lot_id===l.id).length;return n<2?'#16a34a':n<3?'#eab308':'#dc2626'}if(view==='Cumplimiento del objetivo')return m.compliance>=100?'#16a34a':m.compliance>=85?'#eab308':'#dc2626';if(view==='Tendencia productiva')return m.trend==='Creciente'?'#16a34a':m.trend==='Decreciente'?'#dc2626':'#eab308';const metric=view==='Producción estimada campaña actual'?m.objective?.estimated_kg_ha:view==='Promedio 5 campañas'?m.mean5:view==='Mejor campaña histórica'?m.best?.kg_ha:view==='Objetivo campaña actual'?m.objective?.kg_ha:view==='kg/planta'?(m.last?.kg_plant||0)*700:m.last?.kg_ha;if(!['Cultivo','Variedad','Edad','Año de plantación','Densidad'].includes(view))return metric>=ranges.high?'#16a34a':metric>=ranges.low?'#eab308':'#dc2626';const key=view==='Variedad'?l.variety:view==='Cultivo'?l.crop:view==='Edad'?new Date().getFullYear()-l.planting_year:view==='Densidad'?10000/(l.row_spacing*l.plant_spacing):l.planting_year;return categorical[Math.abs(String(key).split('').reduce((a,c)=>a+c.charCodeAt(0),0))%categorical.length]};const center=lots[0]?.polygon?.[0]||[-33.03,-68.88];return <div className="relative h-[calc(100vh-4rem)]"><MapContainer center={center} zoom={15} className="h-full w-full" zoomControl><TileLayer attribution="&copy; Esri" url="https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"/>{lots.map(l=><Polygon key={l.id} positions={l.polygon} pathOptions={{color:'#fff',weight:2,fillColor:color(l),fillOpacity:.62}} eventHandlers={{click:()=>nav(`/lotes/${l.id}`)}}><Tooltip permanent direction="center" className="lot-label">{l.code}</Tooltip></Polygon>)}</MapContainer><div className="absolute left-4 top-4 z-[1000] w-[min(360px,calc(100%-2rem))]"><MapFilters view={view} setView={setView} filters={filters} setFilters={setFilters} lots={d.Lot||[]}/></div><div className="absolute bottom-5 right-4 z-[1000] rounded-xl bg-white/95 px-4 py-3 text-xs shadow-xl"><b>{lots.length} lotes visibles</b><p className="mt-1 text-slate-500">Hacé clic en un polígono para abrir su ficha.</p></div></div>}