import React,{useState} from 'react';
import { X } from 'lucide-react';
import { backend } from '@/api/backendClient';
import { polygonAreaHa } from '@/lib/farmCalculations';
export default function LotFormModal({lot,polygon,onSaved,onClose}){
  const area=Math.max(0.1,+polygonAreaHa(polygon).toFixed(1));
  const [form,setForm]=useState(lot?{...lot}:{name:'',farm:'',sector:'',crop:'',variety:'',planting_year:new Date().getFullYear(),row_spacing:5,plant_spacing:3,area_ha:area,soil_type:''});
  const [busy,setBusy]=useState(false);
  const set=(k,v)=>setForm({...form,[k]:v});
  const VARS={Olivos:['Coratina','Barnea','Hojiblanca','Picual','Arbequina','Arbosana'],Granadas:['Wonderful']};
  const setCrop=c=>setForm({...form,crop:c,variety:(VARS[c]||[''])[0]});
  const save=async e=>{e.preventDefault();setBusy(true);
    if(lot) await backend.entities.Lot.update(lot.id,{polygon,area_ha:Number(form.area_ha)});
    else await backend.entities.Lot.create({...form,planting_year:Number(form.planting_year),row_spacing:Number(form.row_spacing),plant_spacing:Number(form.plant_spacing),area_ha:Number(form.area_ha),polygon});
    await onSaved(); setBusy(false); onClose();
  };
  const f=(k,label,type='text')=> <label className="grid gap-1 text-xs font-bold uppercase text-slate-500">{label}<input type={type} value={form[k]??''} onChange={e=>set(k,e.target.value)} required className="rounded-lg border px-3 py-2 text-sm normal-case text-slate-800"/></label>;
  return <div className="fixed inset-0 z-[2000] grid place-items-center bg-black/50 p-4"><form onSubmit={save} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-bold">{lot?'Guardar polígono':'Nuevo lote'}</h2><button type="button" onClick={onClose}><X/></button></div>{!lot && <div className="grid gap-3 sm:grid-cols-2">{f('name','Nombre')}{<label key="farm" className="grid gap-1 text-xs font-bold uppercase text-slate-500">Finca<select value={form.farm??''} onChange={e=>set('farm',e.target.value)} required className="rounded-lg border px-3 py-2 text-sm normal-case text-slate-800"><option value="">Seleccionar…</option><option>Las 500</option><option>Glonet</option><option>Las 115</option></select></label>}{<label key="sector" className="grid gap-1 text-xs font-bold uppercase text-slate-500">Sector<select value={form.sector??''} onChange={e=>set('sector',e.target.value)} className="rounded-lg border px-3 py-2 text-sm normal-case text-slate-800"><option value="">Seleccionar…</option>{['NO','NE','SO','SE','E','C','O'].map(s=><option key={s}>{s}</option>)}</select></label>}{<label key="crop" className="grid gap-1 text-xs font-bold uppercase text-slate-500">Cultivo<select value={form.crop??''} onChange={e=>setCrop(e.target.value)} required className="rounded-lg border px-3 py-2 text-sm normal-case text-slate-800"><option value="">Seleccionar…</option><option>Olivos</option><option>Granadas</option></select></label>}{<label key="variety" className="grid gap-1 text-xs font-bold uppercase text-slate-500">Variedad<select value={form.variety??''} onChange={e=>set('variety',e.target.value)} required className="rounded-lg border px-3 py-2 text-sm normal-case text-slate-800"><option value="">Seleccionar…</option>{(VARS[form.crop]||[]).map(v=><option key={v}>{v}</option>)}</select></label>}{f('planting_year','Año plantación','number')}{f('row_spacing','Marco filas (m)','number')}{f('plant_spacing','Marco plantas (m)','number')}{f('area_ha','Superficie (ha)','number')}{f('soil_type','Tipo de suelo')}</div>}<p className="mt-3 text-xs text-slate-500">Superficie calculada del polígono: <b>{area} ha</b>{lot?' (editable abajo)':''}{lot&&<span className="mt-2 block"><label className="grid gap-1 text-xs font-bold uppercase text-slate-500">Superficie (ha)<input type="number" step="0.1" value={form.area_ha} onChange={e=>set('area_ha',e.target.value)} className="rounded-lg border px-3 py-2 text-sm normal-case text-slate-800"/></label></span>}</p><button disabled={busy} className="mt-5 w-full rounded-xl bg-emerald-900 py-3 font-bold text-white">{busy?'Guardando…':'Guardar lote'}</button></form></div>;}